services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/app:delegated
    ports:
      - "8081:80"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
